version: '3.8'

services:
  gomarket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomarket-app
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - gomarket-network

networks:
  gomarket-network:
    driver: bridge

